name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        arch: [x86, x64]
        exclude:
        - os: ubuntu
          arch: x86
        - os: macos
          arch: x86
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
      with:
        arch: ${{ matrix.arch }}
    - run: luamake
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: lua-debug
        path: publish
  publish:
    runs-on: macos-latest
    needs: compile
    steps:
      - run: npm install -g vsce
      - uses: actions/download-artifact@v1.0.0
        with:
          name: lua-debug
      - run: chmod -v +x lua-debug/runtime/[^w]*/lua5*/lua
      - run: chmod -v +x lua-debug/bin/[^w]*/lua-debug
      - run: cd lua-debug && vsce publish -p ${{ secrets.VSCE_KEY }}
        continue-on-error: true
